name: Docker CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Docker image
      uses: elgohr/Publish-Docker-Github-Action@2.14
      with:
        name: boreddevco/phoenix-elixir
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 1.10
        tags: "1.10.2, latest"
